alias ga='git add'
alias gl='git log --oneline --graph'
alias gc="git commit"
alias gca="git commit --amend"
alias gp="git push"
alias gsw="git switch"
alias gst="git status"
alias gb="git branch"
alias gcl="git clone"
