declare -A ZINIT
ZINIT[BIN_DIR]=/opt/zinit/zinit.git
ZINIT[HOME_DIR]=/opt/zinit
ZINIT[PLUGINS_DIR]=~/.opt/zinit/plugins
ZINIT[COMPLETIONS_DIR]=~/.opt/zinit/completions
ZINIT[SNIPPETS_DIR]=~/.opt/zinit/snippets

ZPFX=~/.opt/zinit/polaris
ZSH_CACHE_DIR=~/.cache/zinit


