# install zinit
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone --depth 1 https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"

source "${ZINIT_HOME}/zinit.zsh"

zinit ice depth"1" wait lucid; zinit light agkozak/zsh-z
zinit ice as"completion" wait lucid blockf atinit"ZINIT[COMPINIT_OPTS]=-C; zpcompinit; zpcdreplay"
zinit snippet https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker
zinit ice depth"1" wait lucid; zinit light zsh-users/zsh-autosuggestions
zinit ice depth"1" wait lucid blockf atinit"ZINIT[COMPINIT_OPTS]=-C; zpcompinit; zpcdreplay"
zinit ice depth"1"; zinit light zsh-users/zsh-syntax-highlighting
zinit ice depth"1"; zinit light romkatv/powerlevel10k
zinit light zsh-users/zsh-completions


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# settings

# history
HISTSIZE=1024
SAVEHIST=1024
HISTFILE="$HOME/.zsh_history"
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.

# enable shift tab

bindkey '^[[Z' reverse-menu-complete

# alias

(( $+commands[nvim] )) && alias vim='nvim'
# ls highlight
if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	alias ls='ls --color=auto'
fi

# git log
# basic
alias gitlog='git log --all --decorate --oneline --graph'
# in case you need more information
#   alias gitlog="git log --date=short --date-order --all --graph --pretty=format:'%C(auto)%h%Creset %C(auto)%d%Creset %s %C(green)(%ad - %cr) %C(bold cyan)<%an>%Creset'"

# proxy
# export PROXY_SERVE=''
alias proxy-on='export ALL_PROXY=$PROXY_SERVE'
alias proxy-off="unset ALL_PROXY"
PROXY_TEST_ADDR="www.google.com"
alias proxy-test='curl -m 3 -s -o /dev/null $PROXY_TEST_ADDR \
	-w "%{http_code} %{time_connect}" | \
	awk "{printf \"$PROXY_TEST_ADDR: Code:%-4d Delay:%.2fms\",\$1,(\$2*1000)}"| \
	xargs -I {} echo "{}"'

# zinit plugins
# set <right> partial accept
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(
	end-of-line
	vi-forward-char
	vi-end-of-line
	vi-add-eol
)
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS=(
	forward-char
	forward-word
	emacs-forward-word
	vi-forward-word
	vi-forward-word-end
	vi-forward-blank-word
	vi-forward-blank-word-end
	vi-find-next-char
	vi-find-next-char-skip
)

autoload -U compinit && compinit
